print()
print("Hallo Welt")
print("Dies ist ein Python-Skript.")
print("Es gibt eine einfache Nachricht auf der Konsole aus.")
print("Du kannst dieses Skript mit dem Python-Interpreter ausführen.")
print("Stelle sicher, dass Python auf deinem System installiert ist.")
print("Um das Skript auszuführen, benutze den Befehl: python hello_world.py")
print()
print("Viel Spaß beim Programmieren in Python!")
print("Du kannst dieses Skript gerne anpassen und erweitern.")
print("Speichere deine Änderungen, bevor du das Skript erneut ausführst.")